aws[patch]: fix ordering of tool result content blocks (#389)
https://github.com/langchain-ai/langgraph/discussions/2161

Anthropic requires that tool result content blocks precede text in user
messages. The functionality to merge messages does not account for this.
```python
from langchain_aws import ChatBedrock
from langchain_core.messages import (
    AIMessage,
    HumanMessage,
    SystemMessage,
    ToolMessage,
)
from langchain_core.tools import tool


@tool
def get_weather(location: str) -> str:
    """Get weather at a location."""
    return "It's sunny."

system = SystemMessage("You are a helpful assistant.")
human = HumanMessage("What is the weather in Boston?")
ai = AIMessage(
    "",
    tool_calls=[
        {"name": "get_weather", "id": "1", "args": {"location": "Boston, MA"}},
    ],
)
tool = ToolMessage(
    "It's sunny.",
    tool_call_id="1",
)
human_2 = HumanMessage("That doesn't look right.")
messages = [system, human, ai, tool, human_2]


llm = ChatBedrock(
    model="anthropic.claude-3-5-sonnet-20240620-v1:0",
).bind_tools([get_weather])

response = llm.invoke(messages)
```
^ Before this PR, this will raise:
> ValidationException: An error occurred (ValidationException) when
calling the InvokeModel operation: messages.2: Did not find 1
`tool_result` block(s) at the beginning of this message. Messages
following `tool_use` blocks must begin with a matching number of
`tool_result` blocks.

cc @laithalsaadoon @andresriancho